server:
  port: 8000
spring:  application:    name: registration_server
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:      defatzone: http://localhost:8761/eureka
  instance:    hostname: localhost